# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:6.8.13

RUN logstash-plugin install logstash-input-redis
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
